[[headers]]
  for = "/*"
  [headers.values]
    # Allow loading images from YouTube domains
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://i.ytimg.com https://img.youtube.com https://i1.ytimg.com https://i2.ytimg.com https://i3.ytimg.com https://i4.ytimg.com; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.openai.com https://*.supabase.co; frame-src 'self' https://www.youtube.com;"
    # CORS headers for API routes
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"